version: '3.9'

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - '8000:8000'
    depends_on:
      - db
    environment:
      - "DJANGO_SECRET_KEY=django-insecure-s073kfrw3c5=b#)1*%0imzz&5*&^vyv=!p9zpf+i488&y7s7^k"
      - "DJANGO_DEBUG=True"

  db:
    image: postgres:14
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
